name: neuralhydrology
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - bokeh
  - h5py
  - hdf5
  - jupyter
  - matplotlib
  - netcdf4
  - numba
  - pandas
  - pip
  - pytest
  - pytest-cov
  - python=3.10
  - ruamel.yaml
  - scipy
  - tqdm
  - xarray
  - yapf
  - pip:
    - torch
    - tensorboard
